summary: Keyboard configuration database for the X Window System
webpage: https://www.freedesktop.org/wiki/Software/XKeyboardConfig/
version: 2.47
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-15.0-arm64/releases/download/2026.08.10.2/xkeyboard-config-2.47-MacOSX-15.0-arm64.tar.xz
bin-sha: 0b29ff2d09d0c54227201aed26d9d50db5258b92749e86af713c73a0ef3a8bfb
